mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/',include('store.urls', namespace='store')),
    path('staff/',include('staff.urls', namespace='staff')),
]

staff/urls.py
from django.urls import path

from . import views
app_name = 'store'

urlpatterns = [
    # path('register/',views.register, name='register'),
    path('login/',views.loginPage, name='login'),
    path('logout/',views.logoutUser, name='logout')
]

store/urls.py
from django.urls import path

from . import views
app_name = 'store'
urlpatterns = [
    path('', views.index, name='index'),
    path('stocks/', views.stocks, name='stocks'),
    path('orders/', views.orders, name='orders'),
    path('medicines/',views.medicines, name='medicines'),
    path('customers/', views.customers, name='customers'),
    path('add_order/', views.addOrder, name='add_order' ),
    path('create_shipping_mode/', views.createShippingMode, name='create_shipping_mode'),
    path('create_customer/',views.createCustomer, name='create_customer'),
    path('create_transaction/', views.createTransaction, name='create_transaction'),
    path('customer_details/<int:pk>',views.customerDetails, name='customer_details'),
    path('create_medicine/', views.createMedicine, name='create_medicine'),
    path('update_stocks/', views.updateStocks, name='update_stocks'),
    path('add_stocks/', views.addStocks, name='add_stocks'),
    path('add_stock_history', views.addStockHistory, name='add_stock_history'),
    path('order_details/<int:pk>',views.orderDetails, name='order_details'),
    path('medicine_details/<int:pk>', views.medicineDetails, name='medicine_details'),
    path('money_transaction_history',views.moneyTransactionHistory, name='money_transaction_history'),
]

store/models.py
from django.db.models.fields.related import ForeignKey
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import User


class ShippingMode(models.Model):
    name = models.CharField(max_length=200, unique=True)
    created_by = models.ForeignKey(User, on_delete=models.PROTECT)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{}'.format(self.name)

class Customer(models.Model):
    name = models.CharField(max_length=200, unique=True)
    balance = models.FloatField(default=0)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number1 = models.CharField(validators=[phone_regex], max_length=15, blank=True)
    phone_number2 = models.CharField(validators=[phone_regex], max_length=15, blank=True)
    phone_number3 = models.CharField(validators=[phone_regex], max_length=15, blank=True)
    email = models.EmailField(max_length=50, blank=True)
    is_dr = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.PROTECT)

    def __str__(self):
        return '{}'.format(self.name)

class Medicine(models.Model):
    name = models.CharField(max_length=100, unique=True)
    code = models.CharField(max_length=200)
    price_peso = models.FloatField()
    price_usd = models.FloatField(blank=True)
    india_code = models.FloatField()
    price_dr = models.FloatField(blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.PROTECT)

    def __str__(self):
        return '{}'.format(self.name)

class Stock(models.Model):
    medicine = models.ForeignKey(Medicine, on_delete=models.PROTECT )
    location = models.CharField(max_length=100)
    quantity = models.IntegerField()
    expiry_date = models.DateField()
    created_on = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.PROTECT)

    def __str__(self) -> str:
        return '{} at {}'.format(self.medicine, self.location)

class Order(models.Model):
    medicine = models.ForeignKey(Medicine, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    customer = models.ForeignKey(Customer, on_delete=models.RESTRICT)
    shipping_mode = models.ForeignKey(ShippingMode, on_delete=models.RESTRICT)
    delivery_date = models.DateField(blank=True, null=True)
    delivery_done = models.BooleanField(default=False)
    payment_done = models.BooleanField(default=False)
    payment_date = models.DateField(blank=True,null=True)
    bank = models.CharField(max_length=200, blank=True)
    from_stock = models.ForeignKey(Stock, on_delete=models.PROTECT)
    created_on = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.PROTECT)

    def __str__(self) -> str:
        return '{} quant. of {}'.format(self.quantity,self.medicine)


class MoneyTransaction(models.Model):
    amount = models.FloatField()
    remarks = models.TextField(max_length=2000)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.PROTECT)

    def __str__(self):
        return '{}'.format(self.amount)

class StockTransaction(models.Model):
    quantity = models.IntegerField()
    stock = models.ForeignKey(Stock, on_delete=models.PROTECT)
    created_on = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.PROTECT)

    def __str__(self):
        return '{} of {}'.format(self.quantity, self.stock)

class StockCreateTransaction(models.Model):
    medicine = models.ForeignKey(Medicine, on_delete=models.PROTECT )
    location = models.CharField(max_length=100, unique=True)
    quantity = models.IntegerField()
    created_on = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.PROTECT)

    def __str__(self):
        return '{} at {}'.format(self.medicine, self.location)



# Create your models here.

store/views.py
from django.shortcuts import redirect, render
from store import forms, models
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.
@login_required()
def index(request):
    messages.success(request, 'welcome to contact.')
    return render(request,template_name="templates/index.html")

@login_required()
def orders(request):
    
    try:
        all_orders = models.Order.objects.order_by('-created_on')
    except models.Order.DoesNotExist:
        all_orders = False


    return render(request, 'templates/orders.html', {'all_orders':all_orders})

@login_required()
def stocks(request):
    all_stock_transactions = models.StockTransaction.objects.order_by('-created_on')
    return render(request, 'templates/stocks.html', {'all_stock_transactions':all_stock_transactions})

@login_required()
def addStocks(request):
    if request.method == "POST":
        form = forms.StockForm(request.POST, creator=request.user)
        print(request.POST)
        print(form.is_valid())
        if form.is_valid():
            medicine = form.cleaned_data.get('medicine')
            location = form.cleaned_data.get('location')
            quantity = form.cleaned_data.get('quantity')
            stock_create_transaction = models.StockCreateTransaction(medicine = medicine,location = location, quantity = quantity, created_by=request.user)
            stock_create_transaction.save()
            form.save()
            messages.success(request, "Stock added successfully")
            return redirect('store:stocks')

    all_medicine = models.Medicine.objects.all()
    return render(request, 'templates/add_stocks.html', {'all_medicine':all_medicine})

@login_required()
def addStockHistory(request):
    all_stock_transactions = models.StockCreateTransaction.objects.order_by('-created_on')
    return render(request, 'templates/add_stock_history.html',{'all_stock_transactions':all_stock_transactions} )

@login_required()
def updateStocks(request):
    if request.method == "POST":
        form = forms.StockTransactionForm(request.POST, creator=request.user)
        if form.is_valid():
            form.save()
            quantity = form.cleaned_data['quantity']
            stock = form.cleaned_data['stock']
            stock.quantity += quantity
            stock.save()
            messages.success(request, "Stock updated successfully")
            return redirect('store:stocks')

    all_stocks = models.Stock.objects.all()
    print(all_stocks)
    
    return render(request, 'templates/update_stocks.html',{'all_stocks':all_stocks})

@login_required()
def medicines(request):
    try:
        all_medicines = models.Medicine.objects.order_by('-created_on')
    except models.Medicine.DoesNotExist:
        all_medicines = False
    return render(request, 'templates/medicines.html',{'all_medicines':all_medicines})

@login_required()
def medicineDetails(request, pk):
    try:
        medicine = models.Medicine.objects.get(pk = pk)
    except models.Medicine.DoesNotExist:
        medicine = False
    return render(request, 'templates/medicine_details.html',{'medicine':medicine})

@login_required()
def customers(request):
    all_customers = models.Customer.objects.order_by('-created_on')
    return render(request, template_name='templates/customers.html',context={'all_customers':all_customers})

@login_required()
def customerDetails(request, pk):
    try:
        customer = models.Customer.objects.get(pk = pk)
        print("customer is ",customer)
    except models.Customer.DoesNotExist:
        print("I*******************************CustomerDoesNotExist")
        customer = False
    
    try:
        customer_orders = models.Order.objects.filter(customer= customer)
    except:
        customer_orders = False
    

    return render(request, template_name='templates/customer_details.html',context={'customer':customer, 'customer_orders':customer_orders})


@login_required()
def createMedicine(request):
        # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = forms.MedicineForm(request.POST,  creator=request.user)
        # check whether it's valid:
        if form.is_valid():
            form.save()
            name = form.cleaned_data.get('name')
            messages.success(request, "{} is created successfully".format(name))
            return HttpResponseRedirect(reverse('store:medicines'))

    # if a GET (or any other method) we'll create a blank form
    else:
        form = forms.MedicineForm()

    return render(request, 'templates/create_medicine.html',context={'form':form})
 
@login_required()
def addOrder(request):
        # if this is a POST request we need to process the form dat
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = forms.OrderForm(request.POST, creator=request.user)
        # check whether it's valid:
        if form.is_valid():
            form.save()
            medicine = models.Medicine.objects.get(pk=request.POST['medicine'])
            customer = models.Customer.objects.get(pk=request.POST['customer'])
            stock = form.cleaned_data.get('from_stock')
            quantity = form.cleaned_data.get('quantity')

            ## update stock
            stock.quantity -= quantity

            ## update customer account
            if customer.is_dr:
                customer.balance -= medicine.price_dr*quantity
            else:
                customer.balance -= medicine.price_peso*quantity
            customer.save()
            medicine.save()
            stock.save()
            return HttpResponseRedirect(reverse('store:orders'))
    # if a GET (or any other method) we'll create a blank form
    all_medicines = models.Medicine.objects.all()
    all_shipping_modes = models.ShippingMode.objects.all()
    all_customers = models.Customer.objects.all()
    all_stocks = models.Stock.objects.all()

    medicine_dict = dict()
    for i in all_medicines:
        medicine_dict[i.name] = i.id

    shipping_modes_dict = dict()
    for i in all_shipping_modes:
        shipping_modes_dict[i.name] = i.id

    customers_dict = dict()
    for i in all_customers:
        customers_dict[i.name] = i.id

    stock_dict = dict()
    for i in all_stocks:
        stock_dict[i.location] = i.id
    
    context = {'all_medicines':medicine_dict,
               'all_customers':customers_dict,
               'all_shipping_modes':shipping_modes_dict,
               'all_stocks':stock_dict}

    return render(request, 'templates/add_order.html',context=context)

@login_required()
def orderDetails(request, pk):
    payment_form = None
    delivery_form = None
    try:
        order = models.Order.objects.get(pk = pk)
        if not order.payment_done:
            payment_form = forms.PaymentDoneForm()
        if not order.delivery_done:
            delivery_form = forms.DeliveryDoneForm()
        if request.method == 'POST':
            print("it's a post reqeust")
            if request.POST['form_type'] == 'delivery' and not order.delivery_done:
                delivery_form = forms.DeliveryDoneForm(request.POST)
                print(request.POST)
                print(delivery_form.is_valid())
                if delivery_form.is_valid():
                    order.delivery_date = delivery_form.cleaned_data.get('delivery_date')
                    order.delivery_done = True
                    order.save()
                    messages.success(request, "Order updated successfully")

            if request.POST['form_type'] == 'payment' and not order.payment_done:
                payment_form = forms.PaymentDoneForm(request.POST)
                print(payment_form.is_valid())
                if payment_form.is_valid():
                    order.payment_date = payment_form.cleaned_data.get('payment_date')
                    order.payment_done = True
                    order.bank = payment_form.cleaned_data.get('bank')
                    order.save()
                    messages.success(request, "Order updated successfully")

    except models.Order.DoesNotExist:
        order = False
    
    context = {
        'payment_form':payment_form,
        'delivery_form':delivery_form,
        'order':order
    }
    
    return render(request, template_name='templates/order_details.html',context=context)

@login_required()
def createTransaction(request):
        # if this is a POST request we need to process the form data
    if request.method == 'POST':
        print("psot method")
        # create a form instance and populate it with data from the request:
        form = forms.MoneyTransactionFrom(request.POST, creator=request.user)
        # check whether it's valid:
        print(request.POST)
        if form.is_valid():
            form.save()
            print("IIIIIIVAlid form")
            customer =form.cleaned_data.get('customer')
            amount = float(form.cleaned_data.get('amount'))
            customer.balance += amount
            customer.save()
            messages.success(request, "Transaction of amount {}, is created successfully".format(amount))
            return HttpResponseRedirect(reverse('store:index'))
    # if a GET (or any other method) we'll create a blank form
    all_customers = models.Customer.objects.all()
    return render(request, 'templates/create_transaction.html',context={'all_customers':all_customers})

@login_required()
def moneyTransactionHistory(request):
    all_money_transactions = models.MoneyTransaction.objects.all()
    return render(request, 'templates/money_transaction_history.html',{'all_money_transactions':all_money_transactions})

@login_required()
def createCustomer(request):

templates/add_stocks.html
{% extends 'templates/base.html' %}

{% block header %}
<script
  src="https://code.jquery.com/jquery-3.6.0.min.js"
  integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
  crossorigin="anonymous"></script>

  <script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
  integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
  crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" integrity="sha512-aOG0c6nPNzGk+5zjwyJaoRUgCdOrfSDhmMID2u4+OIslr0GjpLKo7Xm0Ao3xmpM4T8AmIouRkqwj1nrdVsLKEQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />

  <script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.min.js" integrity="sha512-rMGGF4wg1R73ehtnxXBt5mbUfN9JUJwbk21KMlnLZDJh7BkPmeovBuddZCENJddHYYMkCh9hPFnPmS9sspki8g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.min.css" integrity="sha512-yVvxUQV0QESBt1SyZbNJMAwyKvFTLMyXSyBHDO4BG5t7k/Lw34tyqlSDlKIrIENIzCl+RVUNjmCPG+V/GMesRw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
{% load static %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
<link rel="stylesheet" href="{% static 'css/central.css' %}" />
{% endblock header %}
{% block body %}

{% for message in messages %}
    <p>{{message}}</p>

{% endfor %}
<h1 class="title">Add Stock</h1>
<section class="form">
    <div class="container">
        <form action="{% url 'store:add_stocks' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_location">Location</label> 
                <input type="text" name="location" step="any" required id="id_location">
            </div>
            
            <div class="form-group">
                <label for="id_medicine">Medicine:</label> 
                <select name="medicine" required id="id_medicine" class="chosen">
                    <option value="" selected>Select Medicine</option>
                    {% for medicine in all_medicine %}
                    <option value="{{medicine.id}}">{{medicine.name}}</option>             
                    {% endfor %}
                </select>    
            </div>
            <div class="form-group">
                <label for="id_quantity">Quantity</label> 
                <input type="number" name="quantity" step="any" required id="id_quantity">
            </div>
            <div class="form-group">
                <label for="id_expiry_date">Expiration Date</label> 
                <input type="date" name="expiry_date"  required id="id_expiry_date">
            </div>

            
            <input class="submit_button_small" type="submit" value="Submit">
        
        </form>

    </div>
</section>
{% endblock body %}

{% block scripts %}
<script type="text/javascript">
    $(".chosen").chosen();

</script>

{% endblock scripts %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <title>Document</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/central.css' %}">
    {% block header%}

    {% endblock header%}
</head>
<body>
    <nav class="navbar">
        <div class="brand-title">Brand Name</div>
        <a href="#" class="toggle-button">
          <span class="bar"></span>
          <span class="bar"></span>
          <span class="bar"></span>
          <span class="bar"></span>
          <span class="bar"></span>
          <span class="bar"></span>
        </a>
        <div class="navbar-links">
          <ul>
            <li><a href="{% url 'store:orders' %}">Orders</a></li>
            <li><a href="{% url 'store:customers' %}">Customers</a></li>
            <li><a href="{% url 'store:stocks' %}">Stock</a></li>
            <li><a href="{% url 'store:medicines' %}">Medicines</a></li>
            <li><a href="{% url 'store:create_transaction' %}">Transactions</a></li>
            <li><a href="{% url 'staff:logout' %}">Logout</a></li>
          </ul>
        </div>
    </nav>
    {% for message in messages %}
    <div id="messageDiv" class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
        <strong>Message:</strong>{{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endfor %}
   
    {% block body %}
    {% endblock body%}
</body>
<script>
    const toggleButton = document.getElementsByClassName('toggle-button')[0]
    const navbarLinks = document.getElementsByClassName('navbar-links')[0]

    toggleButton.addEventListener('click', () => {
    navbarLinks.classList.toggle('active')
    })
</script>
<script>
    //remove message
    $(".btn-close").on("click", function(event) {
        $("#messageDiv").remove();
        event.preventDefault();
    });
</script>
<!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script> -->
{% block scripts %}

{% endblock scripts %}
</html>

templates/create_transaction.html
{% extends 'templates/base.html' %}

{% block header %}
<script
  src="https://code.jquery.com/jquery-3.6.0.min.js"
  integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
  crossorigin="anonymous"></script>

  <script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
  integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
  crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" integrity="sha512-aOG0c6nPNzGk+5zjwyJaoRUgCdOrfSDhmMID2u4+OIslr0GjpLKo7Xm0Ao3xmpM4T8AmIouRkqwj1nrdVsLKEQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />

  <script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.min.js" integrity="sha512-rMGGF4wg1R73ehtnxXBt5mbUfN9JUJwbk21KMlnLZDJh7BkPmeovBuddZCENJddHYYMkCh9hPFnPmS9sspki8g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.min.css" integrity="sha512-yVvxUQV0QESBt1SyZbNJMAwyKvFTLMyXSyBHDO4BG5t7k/Lw34tyqlSDlKIrIENIzCl+RVUNjmCPG+V/GMesRw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
{% load static %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock header %}
{% block body %}
<h1>Create Transaction</h1>
<section class="form">
    <div class="container">
        <form action="{% url 'store:create_transaction' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_amount">Amount:</label> 
                <input type="number" name="amount" step="any" required id="id_amount">
            </div>
            
            <div class="form-group">
                <label for="id_remarks">Remarks:</label> 
                <textarea name="remarks" cols="40" rows="10" maxlength="2000" required id="id_remarks"></textarea>
            </div>
            
            <div class="form-group">
                <label for="id_customer">Customer:</label> 
                <select name="customer" required id="id_customer" class="chosen">
                    <option value="" selected>Select customer</option>
                    {% for customer in all_customers %}
                    <option value="{{customer.id}}">{{customer.name}}</option>             
                    {% endfor %}
                </select>    
            </div>
            
            <input class="submit_button_small" type="submit" value="Submit">
        
        </form>

    </div>
</section>
{% endblock body %}

{% block scripts %}
<script type="text/javascript">
    $(".chosen").chosen();

</script>

{% endblock scripts %}

templates/index.html
{% extends 'templates/base.html' %}


{% block body %}

<!-- <a class="list" href="{% url 'store:orders' %}" >orders</a> <br>
<a href="{% url 'store:stocks' %}">stock</a><br>
<a href="{% url 'store:customers' %}">customer</a><br>
<a href="{% url 'store:medicines' %}">medicine</a><br>
<a href="{% url 'store:create_transaction' %}">Add Transaction</a><br>
<a href="{% url 'store:money_transaction_history' %}">Transaction History</a> -->
<h1 class="title">Welcome to database!</h1>
<p class="title">Use buttons in navigation bar to go to other pages.</p>
{% endblock body %}

templates/medicines.html
{% extends 'templates/base.html' %}

{% block header %}
{% load static %}
    <link rel="stylesheet" href="{% static 'css/central.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <style>

    </style>
{% endblock header %}



{% block body %}
<h1 class="title">Medicine</h1>

<a class="link_button" href="{% url 'store:create_medicine' %}">Create Medicine</a>
<br>
<hr>
<h2 class="title">Medicine List</h2>
{% if all_medicines %}
<input id="myInput" type="text" placeholder="Search..">
<table class="order_table" >
    <thead>
        <tr>
            <th>Name</th>
            <th>Price (PHP)</th>
            <th>Stock </th>
            <th>Stock </th>
        </tr>
    </thead>
    
    {% for medicine in all_medicines %}
    <tbody id="myTable">
        <tr  onclick="window.location.href='http://localhost:8000/store/medicine_details/{{medicine.id}}';">
            <th>{{medicine.name}}</th>
            <th>{{medicine.price_peso}}</th>
            {% if medicine.stock_set.all.0 %}
            <th>{{medicine.stock_set.all.0.quantity}} at {{medicine.stock_set.all.0.location}} </th>
            {% else %}
            <th>-</th>
            {% endif %}
            {% if medicine.stock_set.all.1 %}
            <th>{{medicine.stock_set.all.1.quantity}} at {{medicine.stock_set.all.1.location}}</th>
            {% else %}
            <th>-</th>
            {% endif %}
        </tr>
    </tbody>
    {% endfor %}
</table>
{% else %}
<p>No medicine to show.</p>
{% endif %}
{% endblock body %}




{% block scripts %}
<script>
    $(document).ready(function(){
        $("#myInput").on("keyup", function() {
          var value = $(this).val().toLowerCase();
          $("#myTable tr").filter(function() {
            $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
          });
        });
      });
</script>
{% endblock scripts %}

templates/stocks.html
{% extends 'templates/base.html' %}

{% block header %}
{%load static %}
<link rel="stylesheet" href="{% static 'css/central.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% endblock header %}

{% block body %}
<h1 class="title">Stocks</h1>
<a class="link_button" href="{% url 'store:update_stocks' %}">Update Stocks</a>
<a class="link_button" href="{% url 'store:add_stock_history' %}">History</a>
<a class="link_button" href="{% url 'store:add_stocks' %}">Add Stocks</a>

<hr>

<!-- update history -->
<h2 class="title">Update history</h2>

{% if all_stock_transactions %}
  <input id="myInput" type="text" placeholder="Search..">
  <div id="myDIV">
  {% for transaction in all_stock_transactions %}
    <div style="margin-left: 10px;">
      <p> {{transaction.quantity}} | {{transaction.stock.medicine.name}} at {{transaction.stock.location}}| Handled by: {{user}}</p>
    </div>
    <hr>
  {% endfor %}
  </div>
{%else%}
  <p>No History found.</p>
{% endif %}
{% endblock body %}


<!-- Scripts -->
{% block scripts %}
<script>
    $(document).ready(function(){
        $("#myInput").on("keyup", function() {
          var value = $(this).val().toLowerCase();
          $("#myTable tr").filter(function() {
            $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
          });
        });
      });
</script>
<script>
  $(document).ready(function(){
    $("#myInput").on("keyup", function() {
      var value = $(this).val().toLowerCase();
      $("#myDIV *").filter(function() {
        $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
      });
    });
  });
</scrip>
{% endblock scripts %}